### PR TITLE
fix various issues

### PR DESCRIPTION
**Pull request by cpaulik**
See and review:

Most important changes of which some might be controversial:
- Note and Important
- Change Feature list to heading
- Change TODOS to actual org TODOS

### CODE REVIEW

**Comment by CestDiego** [comment]
@cpaulik could you plz pull the next parts of the conversions? I made some synchronizations. :) Also I'll try to merge this but it's having a conflict because I modified similar stuff on my end. Don't know how to proceed :( I will try to stash my changes and revert to the HEAD that you did edits on.

**Comment by cpaulik** [comment]
I'm not reviewing the next PR's now. If I have time tomorrow I'll pull your branches first. 

I've rebased the PR and it should work now.

**Comment by cpaulik** [comment]
I'm not reviewing the next PR's now. If I have time tomorrow I'll pull your branches first. 

I've rebased the PR and it should work now.

**Comment by CestDiego** [comment]
Ok thanks for the help :) Did you edit your PR? I can merge it automatically now and haven't reset the head yet :O

**Comment by cpaulik** [comment]
Yes I rebased it on your branch.

In magit `F -r F` and then I fixed the merge conflicts.

**Comment by CestDiego** [comment]
Oh Awesome, thanks :D

**Pull request merged**
